version: '3.5'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    network_mode: host
    volumes:
      - homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    
volumes:
  homeassistant-config:
