version: "3.5"
services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    command:
      - duplicati-server
      - --webservice-interface=any
      - --webservice-allowed-hostnames=*
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - duplicati-data:/data
    ports:
      - 8200:8200
    restart: unless-stopped

volumes:
  duplicati-data:
